# Generated by Django 6.0.4 on 2026-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=200)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('cycle_used', models.FloatField(default=0)),
                ('driver_name', models.CharField(default='John Doe', max_length=100)),
                ('carrier_name', models.CharField(default='Logistics Inc', max_length=100)),
                ('truck_number', models.CharField(default='T-100', max_length=50)),
                ('trailer_number', models.CharField(default='TR-500', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Planned', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
